@startuml

class Dot {
  + DotType type
  + DotSpace space
  + String spaceId
  + Json spaceContent
}

class DotType {
}
note right: "Dot 类型"

class DotSpace {
  + String id
  + Object space
  + DotType type
}

Dot *- "1" DotType : 具象化依据
Dot *- "1" DotSpace : 具象化载体

@enduml