@startuml

header 烛火录

title 规范化接口相应

package o.w.o.server.io.api {
  class API {
    + Boolean success
    + Integer code
    + String message
    + String timestamp
  }

  class APIResult extends API {
    + Object payload
  }

  class Page<T> {
    + List<T> list
    + Integer size
    + Integer page
    + Integer totalPages
    + Integer totalSize
  }

  class APIPageableResult<T> extends APIResult {
    + Page<T> payload
  }

  APIPageableResult -> Page

  class APIException extends API {
    + String path
    + List[] errors
  }
}

@enduml