@startuml
header 烛火录
footer Page %page% of %lastpage%

title 接口授权与认证

autonumber

actor "User 用户" as User
boundary Server
control "Authorization 授权服务" as Authorization
control "Authentication 认证服务" as Authentication
control Service
database Redis

== 授权 ==

User -> Server : 请求授权 ** POST api/authentication **
Server -> Authorization : 授权校验 **(username - password)**
Authorization -> Authorization : 校验通过，生成 Token
Authorization -> Redis : 存放 (key=id,value=AuthorizedJwtStore) Token
Authorization -> Server
Server -> User : 认证成功返回 Token

== 认证 ==

User -> Server : 请求服务 ** POST api/xxx **
Server -> Authentication : 权限认证 **(Authorization: Token)**
Authentication -> Redis : 获取 服务端 Token
Redis -> Authentication : 获取 服务端 Token
Authentication -> Authentication : Token 校验通过
Authentication -> Service : 执行服务
Service -> Server
Server -> User

@enduml
